name: Build nomad-driver-triton plugin on alpine linux

on:
  push:
    branches: [ master, docker-auth-v1 ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
          name: Create Release
          runs-on: ubuntu-latest
          outputs:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              tag: ${{ steps.build_tag.outputs.tag }}
          steps:
              - name: Create Time Stamp Tag
                id: build_tag
                run: date +'::set-output name=tag::%Y-%m-%d_%H-%M-%S'

              - name: Create Release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ steps.build_tag.outputs.tag }}
                    release_name: Release ${{ steps.build_tag.outputs.tag }}
                    draft: false
                    prerelease: false

  build:
    needs: prepare
    name: Build on alpine
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build go plugin binary
      run: |
        set -xe
        tar=nomad-driver-triton_alpine.tar
        docker build --tag $tag .
        container=$(docker create $tag)
        docker cp $container:/root/go/bin/nomad-driver-triton - > $tar
        docker rm $container
        docker rmi $tag
        xz $tar

    - name: Upload Release Asset
              id: upload_release_asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.prepare.outputs.upload_url }}
                  asset_path: ./nomad-driver-triton_alpine.tar.xz
                  asset_name: nomad-driver-triton_alpine-${{ needs.prepare.outputs.tag }}.tar.xz
                  asset_content_type: application/x-xz

